# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Treekanga < Formula
  desc "Git Worktree Manager"
  homepage "https://github.com/garrettkrohn/treekanga"
  version "0.1.5-beta"
  license "MIT"

  depends_on "tmux"
  depends_on "zoxide"

  on_macos do
    on_intel do
      url "https://github.com/garrettkrohn/treekanga/releases/download/v0.1.5-beta/treekanga_Darwin_x86_64.tar.gz"
      sha256 "84b9cb1b5e4a74b50a14810b083ec4576e26929302148e2312c2b7f849c6e5dc"

      def install
        bin.install "treekanga"
      end
    end
    on_arm do
      url "https://github.com/garrettkrohn/treekanga/releases/download/v0.1.5-beta/treekanga_Darwin_arm64.tar.gz"
      sha256 "5eabb213f9eb6cecb7e771a27d1331fdcdae5f82a539eb76a1c71e879d8ff9ae"

      def install
        bin.install "treekanga"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/garrettkrohn/treekanga/releases/download/v0.1.5-beta/treekanga_Linux_x86_64.tar.gz"
        sha256 "9145f00eddd7f0e4e6ed307e69abf18c05e2f13479c6810f3765b777893ebf92"

        def install
          bin.install "treekanga"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/garrettkrohn/treekanga/releases/download/v0.1.5-beta/treekanga_Linux_arm64.tar.gz"
        sha256 "e976a96a8e88c95f768651a5b22526e087865b901261d58b3b9016cf0434ed24"

        def install
          bin.install "treekanga"
        end
      end
    end
  end
end
