# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Treekanga < Formula
  desc "Git Worktree Manager"
  homepage "https://github.com/garrettkrohn/treekanga"
  version "1.0.13"
  license "MIT"

  depends_on "tmux"
  depends_on "zoxide"

  on_macos do
    on_intel do
      url "https://github.com/garrettkrohn/treekanga/releases/download/v1.0.13/treekanga_Darwin_x86_64.tar.gz"
      sha256 "60ee4d77ff6f7064990d923d8ef752043ca46589d2302c24f8779561fafc5968"

      def install
        bin.install "treekanga"
      end
    end
    on_arm do
      url "https://github.com/garrettkrohn/treekanga/releases/download/v1.0.13/treekanga_Darwin_arm64.tar.gz"
      sha256 "4e1f7d5998af0e6ded06fc4a3f009d66507a3fc5b1d68bec5fbdfee67df27197"

      def install
        bin.install "treekanga"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/garrettkrohn/treekanga/releases/download/v1.0.13/treekanga_Linux_x86_64.tar.gz"
        sha256 "997145cb67d8109cbf505540607d72e5b3f31253e18f9458a85faddcee47f509"

        def install
          bin.install "treekanga"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/garrettkrohn/treekanga/releases/download/v1.0.13/treekanga_Linux_arm64.tar.gz"
        sha256 "b4438281a1666fefa1183fa6ab35adef551896d74aba383e21cc1a9386b3c056"

        def install
          bin.install "treekanga"
        end
      end
    end
  end
end
