# This file was generated by GoReleaser. DO NOT EDIT.
cask "treekanga" do
  desc "Git Worktree Manager"
  homepage "https://github.com/garrettkrohn/treekanga"
  version "1.0.25"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "treekanga"
  depends_on formula: [
      "tmux",
      "zoxide",
    ]

  on_macos do
    on_intel do
      url "https://github.com/garrettkrohn/treekanga/releases/download/v1.0.25/treekanga_Darwin_x86_64.tar.gz"
      sha256 "8c677de8eab496384bd7d4923ea4ef28f8e23a39bca817bd073e7a20b0327a1b"
    end
    on_arm do
      url "https://github.com/garrettkrohn/treekanga/releases/download/v1.0.25/treekanga_Darwin_arm64.tar.gz"
      sha256 "3267f010fa5a49d0e9aef8a39e4d52afba0c27f7dd38fbebb63a3bbf057a5ab4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/garrettkrohn/treekanga/releases/download/v1.0.25/treekanga_Linux_x86_64.tar.gz"
      sha256 "505115d37945a7ca0c1051d1e1c940b7679883ccb182b464c013d3e1b35243db"
    end
    on_arm do
      url "https://github.com/garrettkrohn/treekanga/releases/download/v1.0.25/treekanga_Linux_arm64.tar.gz"
      sha256 "3377f19113e1c7ad62824ae9800125ff94dd986253e4e8151a55228a1a5cb44b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/treekanga"]
    end
  end

  # No zap stanza required
end
